### ISSUE TITLE
domain_create() call returns Command syntax error

### ISSUE THREAD

**Issue by acidjunk** [datahaven-net/epp-python-client#21]
This library looks promising. Managed to get it working against sidn.nl

But after login; when I try to register a domain it returns a `Command syntax error`. Probably something I am doing wrong with the parameters. As these functions have no documentation, types or tests it's quite difficult to investigate what the correct arguments are. Only `domain_name` an `registrar` seem mandatory. With a bit of info I might be able to increase the test-coverage.

**Comment by vesellov** [comment]
Hi Rene.

Sidn.nl looks like a Registry system for .NL zone...  just curious, is it running COCCA back-end or something else? this library I tested only with our own Registry for .AI zone which is running COCCA.

Here is a test case for a `domain_create` EPP command: https://github.com/datahaven-net/epp-python-client/blob/master/tests/epp/test_rpc_server.py#L628

Are you using epp client directly?  Or you have RPC server running in between of your APP/web-site and sidn.nl ?

You will get `Command syntax error` from the back-end if your input payload is wrong. As per my experience with EPP protocol that may happen due to multiple reasons. All of the related instances must be already existing on the back-end: nameservers, contacts, registrants...  

Also it could be that sidn.nl have some additional extensions enabled that require input payload to contain more information... 

Check it out: https://stackoverflow.com/questions/42511645/command-syntax-error-on-epp-domain-create

If you found something needed to be added to the library - let's do it.!

**Comment by acidjunk** [comment]
Hi Veselin,

thanks for the reply. I'm currently using the standalone mode; so I completely missed the tests of the RPC part. Mea culpa. Very nice! I used the stackoverflow example (posted it as raw XML) and that gave me a better error message.

This example gives me:  `<result code="2303"><msg>The specified contact person is unknown.</msg></result>`

```xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
    <epp xmlns="urn:ietf:params:xml:ns:epp-1.0">
    <command>
    <create>
    <domain:create xmlns:domain="urn:ietf:params:xml:ns:domain-1.0">
    <domain:name>floemp.nl</domain:name>
    <domain:period unit="m">12</domain:period>
    <domain:ns>
    <domain:hostObj>ns1.yourdomain.com</domain:hostObj>
            </domain:ns>
    <domain:registrant>TES093515-X1584</domain:registrant>
    <domain:contact type="admin">TES093515-X1584</domain:contact>
        <domain:contact type="tech">TES093515-X1584</domain:contact>
    <domain:contact type="billing">TES093515-X1584</domain:contact>
    <domain:authInfo>
    <domain:pw>qcbJsi68k-;P04QxVTKsU</domain:pw>
    </domain:authInfo>
    </domain:create>
    </create>
    <clTRID>1477398822-5wsm4XbVrt</clTRID>
    </command>
    </epp>
```

The output of the `domain_create()` call from the epp-python-client, with a small change in `make_ctrlid()` so it returns the exact same id:

```xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<epp xmlns="urn:ietf:params:xml:ns:epp-1.0">
    <command>
        <create>
            <domain:create xmlns:domain="urn:ietf:params:xml:ns:domain-1.0">
                <domain:name>floemp.nl</domain:name>
                <domain:registrant>TES093515-X1584</domain:registrant>
                <domain:period unit="m">12</domain:period>
                <domain:ns><domain:hostObj>ns1.yourdomain.com</domain:hostObj></domain:ns>
                <domain:contact type="admin">TES093515-X1584</domain:contact>
                <domain:contact type="billing">TES093515-X1584</domain:contact>
                <domain:contact type="tech">TES093515-X1584</domain:contact>
                <domain:authInfo><domain:pw>qcbJsi68k-;P04QxVTKsU</domain:pw></domain:authInfo>
            </domain:create>
        </create>
        <clTRID>1477398822-5wsm4XbVrt</clTRID>
    </command>
</epp>
```

Which yields: `<result code="2001"><msg>Command syntax error</msg></result>`

After some debugging: I discovered that it seems to be caused by the ordering. When I moved the "domain:registrant" after the name servers; it accepted the XML. I'm not sure if that's part of any RFC/IETF spec or because SIDN.nl uses some weird implementation of a backend. (I don't know what they use; maybe there is some truth in the comments at stack overflow?)

in XML order can be important, though:
https://stackoverflow.com/questions/1131495/in-xml-is-order-important

So I don't know if I should create a PR; that might break your implementation against your backend.

**Comment by vesellov** [comment]
Yes, Rene. please create a PR.

For COCCA back-end the order of the fields inside XML payload doesn't matter - I am pretty confident about that.
Very strange that SIDN.NL is complaining about that.... there is nothing mentioned about that in the RFC which I used to build the library: https://datatracker.ietf.org/doc/html/rfc5731#section-3.2.1

If your back-end also has some additional restrictions on `clTRID` field format then we can add a customized callback method in `EPPConnection()` class which will be used instead of direct call to `make_cltrid()`. So you and me will be able to use a different formats.

**Comment by acidjunk** [comment]
Here you go; but I still have to test it against a live environment, especially regarding the `make_cltrid()` method.

BTW: The bitdust project seems like a very nice concept. If you need help testing iOS, Mac OS or Linux variants; just let me know.

**Comment by acidjunk** [comment]
Thanks for the merge! There will probably be other calls in SIDN that also depend on order; will fix them when I encounter problems with it. Closing the ticket.
